In [3]:
import pandas as pd

df1 = pd.read_csv(
    "/kaggle/input/datasets/nikitabisht/menstrual-cycle-data/FedCycleData071012 (2).csv"
)

df2 = pd.read_csv(
    "/kaggle/input/datasets/echekwuelijah/fertility-and-menstrual-health-data/FedCycleData071012.csv"
)

print("Dataset 1 Shape:", df1.shape)
print("Dataset 2 Shape:", df2.shape)

print("\n")

print(df1.head())

print("\n")

print(df2.head())

Dataset 1 Shape: (1665, 80)
Dataset 2 Shape: (1665, 80)


  ClientID  CycleNumber  Group  CycleWithPeakorNot  ReproductiveCategory  \
0  nfp8122            1      0                   1                     0
1  nfp8122            2      0                   1                     0
2  nfp8122            3      0                   1                     0
3  nfp8122            4      0                   1                     0
4  nfp8122            5      0                   1                     0

   LengthofCycle MeanCycleLength EstimatedDayofOvulation LengthofLutealPhase  \
0             29           27.33                      17                  12
1             27                                      15                  12
2             29                                      15                  14
3             27                                      15                  12
4             28                                      16                  12

  FirstDayofHigh  ... Method Prevmethod Methoddate Whychart Nextpreg  \
0             12  ...      9                              2        7
1             13  ...
2                 ...
3             13  ...
4             12  ...

  NextpregM Spousesame SpousesameM Timeattemptpreg              BMI
0         7          1           1               0  21.254724111867
1
2
3
4

[5 rows x 80 columns]


  ClientID  CycleNumber  Group  CycleWithPeakorNot  ReproductiveCategory  \
0  nfp8122            1      0                   1                     0
1  nfp8122            2      0                   1                     0
2  nfp8122            3      0                   1                     0
3  nfp8122            4      0                   1                     0
4  nfp8122            5      0                   1                     0

   LengthofCycle MeanCycleLength EstimatedDayofOvulation LengthofLutealPhase  \
0             29           27.33                      17                  12
1             27                                      15                  12
2             29                                      15                  14
3             27                                      15                  12
4             28                                      16                  12

  FirstDayofHigh  ... Method Prevmethod Methoddate Whychart Nextpreg  \
0             12  ...      9                              2        7
1             13  ...
2                 ...
3             13  ...
4             12  ...

  NextpregM Spousesame SpousesameM Timeattemptpreg              BMI
0         7          1           1               0  21.254724111867
1
2
3
4

[5 rows x 80 columns]

In [4]:
print("=" * 80)
print("Shape:", df1.shape)

print("\n")

print(df1.info())

print("\n")

print(df1.columns.tolist())

================================================================================
Shape: (1665, 80)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1665 entries, 0 to 1664
Data columns (total 80 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ClientID                    1665 non-null   object
 1   CycleNumber                 1665 non-null   int64
 2   Group                       1665 non-null   int64
 3   CycleWithPeakorNot          1665 non-null   int64
 4   ReproductiveCategory        1665 non-null   int64
 5   LengthofCycle               1665 non-null   int64
 6   MeanCycleLength             1665 non-null   object
 7   EstimatedDayofOvulation     1665 non-null   object
 8   LengthofLutealPhase         1665 non-null   object
 9   FirstDayofHigh              1665 non-null   object
 10  TotalNumberofHighDays       1665 non-null   object
 11  TotalHighPostPeak           1665 non-null   object
 12  TotalNumberofPeakDays       1665 non-null   object
 13  TotalDaysofFertility        1665 non-null   object
 14  TotalFertilityFormula       1665 non-null   object
 15  LengthofMenses              1665 non-null   object
 16  MeanMensesLength            1665 non-null   object
 17  MensesScoreDayOne           1665 non-null   object
 18  MensesScoreDayTwo           1665 non-null   object
 19  MensesScoreDayThree         1665 non-null   object
 20  MensesScoreDayFour          1665 non-null   object
 21  MensesScoreDayFive          1665 non-null   object
 22  MensesScoreDaySix           1665 non-null   object
 23  MensesScoreDaySeven         1665 non-null   object
 24  MensesScoreDayEight         1665 non-null   object
 25  MensesScoreDayNine          1665 non-null   object
 26  MensesScoreDayTen           1665 non-null   object
 27  MensesScoreDay11            1665 non-null   object
 28  MensesScoreDay12            1665 non-null   object
 29  MensesScoreDay13            1665 non-null   object
 30  MensesScoreDay14            1665 non-null   object
 31  MensesScoreDay15            1665 non-null   object
 32  TotalMensesScore            1665 non-null   object
 33  MeanBleedingIntensity       1665 non-null   object
 34  NumberofDaysofIntercourse   1665 non-null   object
 35  IntercourseInFertileWindow  1665 non-null   object
 36  UnusualBleeding             1665 non-null   object
 37  PhasesBleeding              1665 non-null   object
 38  IntercourseDuringUnusBleed  1665 non-null   object
 39  Age                         1665 non-null   object
 40  AgeM                        1665 non-null   object
 41  Maristatus                  1665 non-null   object
 42  MaristatusM                 1665 non-null   object
 43  Yearsmarried                1665 non-null   object
 44  Wedding                     1665 non-null   object
 45  Religion                    1665 non-null   object
 46  ReligionM                   1665 non-null   object
 47  Ethnicity                   1665 non-null   object
 48  EthnicityM                  1665 non-null   object
 49  Schoolyears                 1665 non-null   object
 50  SchoolyearsM                1665 non-null   object
 51  OccupationM                 1665 non-null   object
 52  IncomeM                     1665 non-null   object
 53  Height                      1665 non-null   object
 54  Weight                      1665 non-null   object
 55  Reprocate                   1665 non-null   object
 56  Numberpreg                  1665 non-null   object
 57  Livingkids                  1665 non-null   object
 58  Miscarriages                1665 non-null   object
 59  Abortions                   1665 non-null   object
 60  Medvits                     1665 non-null   object
 61  Medvitexplain               1665 non-null   object
 62  Gynosurgeries               1665 non-null   object
 63  LivingkidsM                 1665 non-null   object
 64  Boys                        1665 non-null   object
 65  Girls                       1665 non-null   object
 66  MedvitsM                    1665 non-null   object
 67  MedvitexplainM              1665 non-null   object
 68  Urosurgeries                1665 non-null   object
 69  Breastfeeding               1665 non-null   object
 70  Method                      1665 non-null   object
 71  Prevmethod                  1665 non-null   object
 72  Methoddate                  1665 non-null   object
 73  Whychart                    1665 non-null   object
 74  Nextpreg                    1665 non-null   object
 75  NextpregM                   1665 non-null   object
 76  Spousesame                  1665 non-null   object
 77  SpousesameM                 1665 non-null   object
 78  Timeattemptpreg             1665 non-null   object
 79  BMI                         1665 non-null   object
dtypes: int64(5), object(75)
memory usage: 1.0+ MB
None


['ClientID', 'CycleNumber', 'Group', 'CycleWithPeakorNot', 'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength', 'EstimatedDayofOvulation', 'LengthofLutealPhase', 'FirstDayofHigh', 'TotalNumberofHighDays', 'TotalHighPostPeak', 'TotalNumberofPeakDays', 'TotalDaysofFertility', 'TotalFertilityFormula', 'LengthofMenses', 'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive', 'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight', 'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11', 'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14', 'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity', 'NumberofDaysofIntercourse', 'IntercourseInFertileWindow', 'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed', 'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding', 'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears', 'SchoolyearsM', 'OccupationM', 'IncomeM', 'Height', 'Weight', 'Reprocate', 'Numberpreg', 'Livingkids', 'Miscarriages', 'Abortions', 'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys', 'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding', 'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg', 'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI']

In [5]:
for col in [
    "LengthofCycle",
    "MeanCycleLength",
    "EstimatedDayofOvulation",
    "LengthofLutealPhase",
    "Age",
    "Height",
    "Weight",
    "BMI"
]:
    print("=" * 70)
    print(col)
    print(df1[col].head(20).tolist())

======================================================================
LengthofCycle
[29, 27, 29, 27, 28, 26, 29, 24, 28, 28, 26, 29, 27, 28, 30, 28, 26, 26, 24, 27]
======================================================================
MeanCycleLength
['27.33', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
======================================================================
EstimatedDayofOvulation
['17', '15', '15', '15', '16', '15', '16', '14', '16', '17', '14', '16', '15', '16', '18', '16', '14', '14', '12', '15']
======================================================================
LengthofLutealPhase
['12', '12', '14', '12', '12', '11', '13', '10', '12', '11', '12', '13', '12', '12', '12', '12', '12', '12', '12', '12']
======================================================================
Age
['36', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
======================================================================
Height
['63', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
======================================================================
Weight
['120', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']
======================================================================
BMI
['21.254724111867', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']

In [8]:
import numpy as np

df = df1.copy()

df = df.replace(r'^\s*$', np.nan, regex=True)

print(df.columns.tolist())

print("\n")

print(df.head())

['ClientID', 'CycleNumber', 'Group', 'CycleWithPeakorNot', 'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength', 'EstimatedDayofOvulation', 'LengthofLutealPhase', 'FirstDayofHigh', 'TotalNumberofHighDays', 'TotalHighPostPeak', 'TotalNumberofPeakDays', 'TotalDaysofFertility', 'TotalFertilityFormula', 'LengthofMenses', 'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive', 'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight', 'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11', 'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14', 'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity', 'NumberofDaysofIntercourse', 'IntercourseInFertileWindow', 'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed', 'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding', 'Religion', 'ReligionM', 'Ethnicity', 'EthnicityM', 'Schoolyears', 'SchoolyearsM', 'OccupationM', 'IncomeM', 'Height', 'Weight', 'Reprocate', 'Numberpreg', 'Livingkids', 'Miscarriages', 'Abortions', 'Medvits', 'Medvitexplain', 'Gynosurgeries', 'LivingkidsM', 'Boys', 'Girls', 'MedvitsM', 'MedvitexplainM', 'Urosurgeries', 'Breastfeeding', 'Method', 'Prevmethod', 'Methoddate', 'Whychart', 'Nextpreg', 'NextpregM', 'Spousesame', 'SpousesameM', 'Timeattemptpreg', 'BMI']


  ClientID  CycleNumber  Group  CycleWithPeakorNot  ReproductiveCategory  \
0  nfp8122            1      0                   1                     0
1  nfp8122            2      0                   1                     0
2  nfp8122            3      0                   1                     0
3  nfp8122            4      0                   1                     0
4  nfp8122            5      0                   1                     0

   LengthofCycle MeanCycleLength EstimatedDayofOvulation LengthofLutealPhase  \
0             29           27.33                      17                  12
1             27             NaN                      15                  12
2             29             NaN                      15                  14
3             27             NaN                      15                  12
4             28             NaN                      16                  12

  FirstDayofHigh  ... Method Prevmethod Methoddate Whychart Nextpreg  \
0             12  ...      9        NaN        NaN        2        7
1             13  ...    NaN        NaN        NaN      NaN      NaN
2            NaN  ...    NaN        NaN        NaN      NaN      NaN
3             13  ...    NaN        NaN        NaN      NaN      NaN
4             12  ...    NaN        NaN        NaN      NaN      NaN

  NextpregM Spousesame SpousesameM Timeattemptpreg              BMI
0         7          1           1               0  21.254724111867
1       NaN        NaN         NaN             NaN              NaN
2       NaN        NaN         NaN             NaN              NaN
3       NaN        NaN         NaN             NaN              NaN
4       NaN        NaN         NaN             NaN              NaN

[5 rows x 80 columns]

In [10]:
df = df.groupby("ClientID").ffill().reset_index()

In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "/kaggle/input/datasets/nikitabisht/menstrual-cycle-data/FedCycleData071012 (2).csv"
)

# Replace blank strings
df = df.replace(r'^\s*$', np.nan, regex=True)

# Forward fill within each patient
df = (
    df.groupby("ClientID", group_keys=False)
      .apply(lambda x: x.ffill())
      .reset_index(drop=True)
)

print(df.shape)
df.head()

/tmp/ipykernel_58/216923309.py:14: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .apply(lambda x: x.ffill())
/tmp/ipykernel_58/216923309.py:14: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.ffill())

(1665, 80)

,ClientID,CycleNumber,Group,CycleWithPeakorNot,ReproductiveCategory,LengthofCycle,MeanCycleLength,EstimatedDayofOvulation,LengthofLutealPhase,FirstDayofHigh,...,Method,Prevmethod,Methoddate,Whychart,Nextpreg,NextpregM,Spousesame,SpousesameM,Timeattemptpreg,BMI
0,nfp8122,1,0,1,0,29,27.33,17,12,12,...,9,NaN,NaN,2,7,7,1,1,0,21.254724111867
1,nfp8122,2,0,1,0,27,27.33,15,12,13,...,9,NaN,NaN,2,7,7,1,1,0,21.254724111867
2,nfp8122,3,0,1,0,29,27.33,15,14,13,...,9,NaN,NaN,2,7,7,1,1,0,21.254724111867
3,nfp8122,4,0,1,0,27,27.33,15,12,13,...,9,NaN,NaN,2,7,7,1,1,0,21.254724111867
4,nfp8122,5,0,1,0,28,27.33,16,12,12,...,9,NaN,NaN,2,7,7,1,1,0,21.254724111867

In [12]:
import numpy as np

# Copy
cycle_df = df.copy()

# Convert numeric columns
numeric_cols = [
    "Age",
    "Height",
    "Weight",
    "BMI",
    "MeanCycleLength",
    "LengthofCycle"
]

for col in numeric_cols:
    cycle_df[col] = pd.to_numeric(cycle_df[col], errors="coerce")

# Sort by woman and cycle
cycle_df = cycle_df.sort_values(
    ["ClientID", "CycleNumber"]
)

# Previous cycle
cycle_df["Prev_Cycle_Length"] = (
    cycle_df.groupby("ClientID")["LengthofCycle"]
    .shift(1)
)

# Previous 2 cycles
cycle_df["Prev2_Cycle_Length"] = (
    cycle_df.groupby("ClientID")["LengthofCycle"]
    .shift(2)
)

# Rolling Mean (last 3 completed cycles)
cycle_df["Rolling_Mean_3"] = (
    cycle_df.groupby("ClientID")["LengthofCycle"]
    .transform(
        lambda x: x.shift(1).rolling(3).mean()
    )
)

# Rolling Std
cycle_df["Rolling_STD_3"] = (
    cycle_df.groupby("ClientID")["LengthofCycle"]
    .transform(
        lambda x: x.shift(1).rolling(3).std()
    )
)

print(cycle_df[[
    "ClientID",
    "CycleNumber",
    "LengthofCycle",
    "Prev_Cycle_Length",
    "Prev2_Cycle_Length",
    "Rolling_Mean_3",
    "Rolling_STD_3"
]].head(15))

   ClientID  CycleNumber  LengthofCycle  Prev_Cycle_Length  \
73  nfp8020            1             27                NaN
74  nfp8020            2             31               27.0
75  nfp8020            3             27               31.0
76  nfp8020            4             28               27.0
77  nfp8020            5             27               28.0
78  nfp8020            6             27               27.0
79  nfp8020            7             27               27.0
80  nfp8020            8             25               27.0
81  nfp8020            9             24               25.0
82  nfp8020           10             18               24.0
83  nfp8020           11             26               18.0
84  nfp8020           12             24               26.0
85  nfp8020           13             27               24.0
86  nfp8020           14             26               27.0
87  nfp8020           15             24               26.0

    Prev2_Cycle_Length  Rolling_Mean_3  Rolling_STD_3
73                 NaN             NaN            NaN
74                 NaN             NaN            NaN
75                27.0             NaN            NaN
76                31.0       28.333333       2.309401
77                27.0       28.666667       2.081666
78                28.0       27.333333       0.577350
79                27.0       27.333333       0.577350
80                27.0       27.000000       0.000000
81                27.0       26.333333       1.154701
82                25.0       25.333333       1.527525
83                24.0       22.333333       3.785939
84                18.0       22.666667       4.163332
85                26.0       22.666667       4.163332
86                24.0       25.666667       1.527525
87                27.0       25.666667       1.527525

In [13]:
from sklearn.model_selection import GroupShuffleSplit

# Remove rows where lag features don't exist
model_df = cycle_df.dropna(
    subset=[
        "Prev_Cycle_Length",
        "Prev2_Cycle_Length",
        "Rolling_Mean_3",
        "Rolling_STD_3"
    ]
).copy()

# Features available BEFORE a cycle starts
FEATURES = [
    "Age",
    "Height",
    "Weight",
    "BMI",
    "CycleNumber",
    "Prev_Cycle_Length",
    "Prev2_Cycle_Length",
    "Rolling_Mean_3",
    "Rolling_STD_3"
]

TARGET = "LengthofCycle"

# Convert to numeric
for col in FEATURES + [TARGET]:
    model_df[col] = pd.to_numeric(
        model_df[col],
        errors="coerce"
    )

# Drop any remaining missing values
model_df = model_df.dropna(subset=FEATURES + [TARGET])

X = model_df[FEATURES]

y = model_df[TARGET]

groups = model_df["ClientID"]

print("="*60)
print("Dataset Shape :", model_df.shape)
print("Unique Women  :", groups.nunique())
print("Target Mean   :", y.mean())
print("Target Std    :", y.std())
print("="*60)

# Group split
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        X,
        y,
        groups
    )
)

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

print("Train:", X_train.shape)
print("Test :", X_test.shape)

print(
    "\nShared Women:",
    len(
        set(groups.iloc[train_idx]).intersection(
            set(groups.iloc[test_idx])
        )
    )
)

============================================================
Dataset Shape : (957, 84)
Unique Women  : 102
Target Mean   : 28.975966562173458
Target Std    : 3.747027724577863
============================================================
Train: (773, 9)
Test : (184, 9)

Shared Women: 0

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import pandas as pd
import numpy as np

models = {
    "Linear Regression": LinearRegression(),

    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    ),

    "CatBoost": CatBoostRegressor(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        loss_function="RMSE",
        random_seed=42,
        verbose=False
    )
}

results = []

predictions = {}

for name, model in models.items():

    print(f"Training {name}...")

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    predictions[name] = pred

    mae = mean_absolute_error(y_test, pred)

    rmse = np.sqrt(mean_squared_error(y_test, pred))

    r2 = r2_score(y_test, pred)

    results.append([
        name,
        mae,
        rmse,
        r2
    ])

results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "MAE",
        "RMSE",
        "R2"
    ]
)

results_df = results_df.sort_values(
    "RMSE"
)

display(results_df)

Training Linear Regression...
Training Random Forest...
Training XGBoost...
Training CatBoost...

               Model       MAE      RMSE        R2
0  Linear Regression  2.396350  3.517154  0.421019
1      Random Forest  2.560598  3.755377  0.339933
3           CatBoost  2.631918  4.016921  0.244790
2            XGBoost  2.855137  4.173662  0.184703

In [15]:
import os
import json
import pickle
import shutil

import joblib
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# =====================================================
# Create Folder Structure
# =====================================================

ROOT = "cycle_length_prediction_engine_v1"

MODELS = os.path.join(ROOT, "models")
REPORTS = os.path.join(ROOT, "reports")
IMAGES = os.path.join(ROOT, "images")

os.makedirs(MODELS, exist_ok=True)
os.makedirs(REPORTS, exist_ok=True)
os.makedirs(IMAGES, exist_ok=True)

# =====================================================
# Save Best Model
# =====================================================

best_model = models["Linear Regression"]

joblib.dump(
    best_model,
    os.path.join(MODELS, "cycle_length_model.pkl")
)

joblib.dump(
    FEATURES,
    os.path.join(MODELS, "feature_columns.pkl")
)

# =====================================================
# Metadata
# =====================================================

metadata = {
    "model_name": "Cycle Length Prediction Engine",
    "version": "v1",
    "algorithm": "Linear Regression",
    "target": TARGET,
    "features": FEATURES,
    "train_samples": int(len(X_train)),
    "test_samples": int(len(X_test)),
    "unique_users": int(groups.nunique())
}

with open(
    os.path.join(MODELS, "model_metadata.json"),
    "w"
) as f:
    json.dump(metadata, f, indent=4)

# =====================================================
# Predictions
# =====================================================

pred = best_model.predict(X_test)

pred_df = X_test.copy()
pred_df["Actual"] = y_test.values
pred_df["Predicted"] = pred
pred_df["Error"] = pred_df["Actual"] - pred

pred_df.to_csv(
    os.path.join(REPORTS, "predictions.csv"),
    index=False
)

# =====================================================
# Metrics
# =====================================================

mae = mean_absolute_error(y_test, pred)
rmse = mean_squared_error(y_test, pred) ** 0.5
r2 = r2_score(y_test, pred)

metrics_df = pd.DataFrame({
    "Metric": ["MAE", "RMSE", "R2"],
    "Value": [mae, rmse, r2]
})

metrics_df.to_csv(
    os.path.join(REPORTS, "model_metrics.csv"),
    index=False
)

# =====================================================
# Training Summary
# =====================================================

with open(
    os.path.join(REPORTS, "training_summary.txt"),
    "w"
) as f:

    f.write("Cycle Length Prediction Engine v1\n")
    f.write("="*50 + "\n\n")

    f.write(f"Algorithm : Linear Regression\n")
    f.write(f"Target    : {TARGET}\n")
    f.write(f"Train     : {len(X_train)}\n")
    f.write(f"Test      : {len(X_test)}\n")
    f.write(f"Users     : {groups.nunique()}\n\n")

    f.write(f"MAE  : {mae:.4f}\n")
    f.write(f"RMSE : {rmse:.4f}\n")
    f.write(f"R2   : {r2:.4f}\n")

# =====================================================
# Actual vs Predicted
# =====================================================

plt.figure(figsize=(8,6))
plt.scatter(y_test, pred)
plt.xlabel("Actual Cycle Length")
plt.ylabel("Predicted Cycle Length")
plt.title("Actual vs Predicted")
plt.grid(True)
plt.tight_layout()
plt.savefig(
    os.path.join(IMAGES, "actual_vs_predicted.png"),
    dpi=300
)
plt.close()

# =====================================================
# Residual Distribution
# =====================================================

residuals = y_test - pred

plt.figure(figsize=(8,6))
plt.hist(residuals, bins=30)
plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.title("Residual Distribution")
plt.grid(True)
plt.tight_layout()
plt.savefig(
    os.path.join(IMAGES, "residual_distribution.png"),
    dpi=300
)
plt.close()

# =====================================================
# Residual Scatter
# =====================================================

plt.figure(figsize=(8,6))
plt.scatter(pred, residuals)
plt.axhline(0, linestyle="--")
plt.xlabel("Predicted")
plt.ylabel("Residual")
plt.title("Residual Scatter")
plt.grid(True)
plt.tight_layout()
plt.savefig(
    os.path.join(IMAGES, "residual_scatter.png"),
    dpi=300
)
plt.close()

# =====================================================
# Zip Everything
# =====================================================

shutil.make_archive(
    ROOT,
    "zip",
    ROOT
)

print("="*60)
print("Everything Saved Successfully!")
print("Folder :", ROOT)
print("ZIP    :", ROOT + ".zip")
print("="*60)

============================================================
Everything Saved Successfully!
Folder : cycle_length_prediction_engine_v1
ZIP    : cycle_length_prediction_engine_v1.zip
============================================================